[2025-05-13 19:39:19.164000Z] Falha na conex√£o com o banco de dados 
[2025-05-13 19:42:11Z] [35m[Deeper_Hub.Core.Logger][0m Falha na conex√£o com o banco de dados 
[2025-05-13 19:43:05Z] [35m[Deeper_Hub.Core.Logger][0m Falha na conex√£o com o banco de dados 
[20:37:07] [35m[Deeper_Hub.Core.Data.Repository][0m [31mFalha ao inserir registro na tabela users[0m reason={:bad_type, {:users, 1, "johndoe", "john@example.com"}} record={:users, 1, "johndoe", "john@example.com"}
